#!/bin/bash

#make all the figures for paper on colors in group catalogues--Campbell 2014.

#figure 1
python mock_colors.py Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle
wait

#figure 2
python mock_groups_HOD.py Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle
wait

#figure 3
python mock_groups_f_L.py Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle
wait

#figure 4
python mock_groups_f_M.py Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle
wait

#figure 5
python mock_groups_CLF.py Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle
wait

#figure 6
python mock_groups_conformity.py Mr19_age_distribution_matching_mock Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle
wait

#figure 7
python mock_groups_HTP.py yang_mocks Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle
wait
python mock_groups_HTP.py berlind_mocks Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle
wait
python mock_groups_HTP.py tinker_mocks Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle
wait

#figure 8
python mock_groups_performance.py Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle
wait


#move all the figures into a folder containing only figures used in the paper.
cp /scratch/dac29/plots/analysis/hearin_mocks/Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle_Mr_colors.pdf  /scratch/dac29/python_scripts/group_color_statistics/paper_figures/fig_1.pdf
cp /scratch/dac29/plots/analysis/groupcats/Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle_HOD.pdf  /scratch/dac29/python_scripts/group_color_statistics/paper_figures/fig_2.pdf
cp /scratch/dac29/plots/analysis/groupcats/Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle_f_L.pdf  /scratch/dac29/python_scripts/group_color_statistics/paper_figures/fig_3.pdf
cp /scratch/dac29/plots/analysis/groupcats/Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle_f_M.pdf  /scratch/dac29/python_scripts/group_color_statistics/paper_figures/fig_4.pdf
cp /scratch/dac29/plots/analysis/groupcats/Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle_CLF.pdf  /scratch/dac29/python_scripts/group_color_statistics/paper_figures/fig_5.pdf
cp /scratch/dac29/plots/analysis/groupcats/conformity_Mr19_age_distribution_matching_mock.pdf  /scratch/dac29/python_scripts/group_color_statistics/paper_figures/fig_6.pdf
cp /scratch/dac29/plots/analysis/berlind_groupcat/Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle_HTP.pdf  /scratch/dac29/python_scripts/group_color_statistics/paper_figures/fig_7a.pdf
cp /scratch/dac29/plots/analysis/tinker_groupcat/Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle_HTP.pdf  /scratch/dac29/python_scripts/group_color_statistics/paper_figures/fig_7b.pdf
cp /scratch/dac29/plots/analysis/yang_groupcat/Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle_HTP.pdf  /scratch/dac29/python_scripts/group_color_statistics/paper_figures/fig_7c.pdf
cp /scratch/dac29/plots/analysis/groupcats/Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle_performance_M.pdf  /scratch/dac29/python_scripts/group_color_statistics/paper_figures/fig_8a.pdf
cp /scratch/dac29/plots/analysis/groupcats/Mr19_age_distribution_matching_mock_sys_empty_shuffle_satrel_shuffle_performance_L.pdf  /scratch/dac29/python_scripts/group_color_statistics/paper_figures/fig_8b.pdf


